### ISSUE TITLE
panic: failed to add already existing miner payout

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/rexplorer#17]
```
panic: failed to add miner payout of 01009a4409b0aa789cbe3b38ae54268557201eb0439c68b61603685794c4a5d024dd1de070a113 to 10000000000: redis:failed to add locked coinoutput dc76aff1ef503a9efc86a944e19de7207fb8d3e2f7fdd0192536e64ed9d384c8 to wallet for 01009a4409b0aa789cbe3b38ae54268557201eb0439c68b61603685794c4a5d024dd1de070a113: trying to add existing locked coin output dc76aff1ef503a9efc86a944e19de7207fb8d3e2f7fdd0192536e64ed9d384c8

goroutine 6 [running]:
main.(*Explorer).ProcessConsensusChange(0xc4201c0840, 0x4cb836d300d6d0b, 0x3c9cb7dda5729c60, 0x77e329b3552bb23a, 0x3b057cdea60f48fe, 0x0, 0x0, 0x0, 0xc420221c70, 0x1, ...)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/explorer.go:215 +0x2505
github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).initializeSubscribe.func1(0xc42035a000, 0x1520230, 0xc42035a000)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:143 +0x294
github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/bbolt.(*DB).View(0xc42029a1e0, 0xc4202136b0, 0x0, 0x0)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/bbolt/db.go:708 +0x90
github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).initializeSubscribe(0xc420264400, 0x1557900, 0xc4201c0840, 0x726687ce1f5c61a1, 0xb96b66336755b5aa, 0x984bea3203c666ea, 0x77f9917f5067f3b1, 0xc4202905a0, 0x1012838, 0x2c0)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:97 +0xbc
github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc420264400, 0x1557900, 0xc4201c0840, 0x726687ce1f5c61a1, 0xb96b66336755b5aa, 0x984bea3203c666ea, 0x77f9917f5067f3b1, 0xc4202905a0, 0x0, 0x0)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:168 +0x174
main.NewExplorer(0x155f5c0, 0xc420080a80, 0x1560260, 0xc420264400, 0x14ddbab, 0x7, 0x7ffeefbff9a1, 0x7, 0x14da3fc, 0x3, ...)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/explorer.go:80 +0x40a
main.(*Commands).Root.func1(0xc420027020, 0xc4202185a0, 0xc420057e70, 0xc420262080, 0xc420080a80, 0x155c3e0, 0xc4200708c0)
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/commands.go:94 +0x7bd
created by main.(*Commands).Root
        /Users/glendc/go/src/github.com/threefoldfoundation/rexplorer/commands.go:52 +0x3a8
```

testnet stats at that point:

```
tfchain network has:
  * a total of 100537670 TFT, of which 100529469.8 TFT is liquid,
    8200.2 TFT is locked, 537670 TFT is paid out as miner payouts
    and 14.10000007 TFT is paid out as tx fees
  * 99.99184% liquid coins of a total of 100537670 TFT coins
  * 00.00816% locked coins of a total of 100537670 TFT coins
  * a block height of 53767, with the time of the highest block
    being 2018-06-20 19:11:39 +0200 CEST (1529514699)
  * a total of 53768 blocks, 148 value transactions and 1445 coin inputs
  * a total of 54179 coin outputs, of which 53455 are liquid, 724 are locked,
    286 transfer value, 53767 are miner payouts and 126 are tx fees
  * a total of 214 unique addresses that have been used
  * an average of 01.93243% value coin outputs per value transaction
  * an average of 00.00275% value transactions per block
  * 98.66369% liquid outputs of a total of 54179 coin outputs
  * 01.33631% locked outputs of a total of 54179 coin outputs
  * 00.27452% value transactions of a total of 53913 transactions
```

**Comment by GlenDC** [comment]
Doesn't seem to be an actual issue, might have been due to some corrupt db. Tried to reproduce and failed to do so.
